"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-09-30 20:09:22.810355

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('keycloak_sub', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('pg', 'supervisor', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keycloak_sub')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('competency', sa.String(length=4), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('quiz', 'voice', 'sup', name='assessmentsource', native_enum=False, length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessments_user_comp', 'assessments', ['user_id', 'competency', 'created_at'], unique=False)
    op.create_table('field_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sup_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('revenue_vnd', sa.BigInteger(), nullable=True),
    sa.Column('dday_units', sa.Integer(), nullable=True),
    sa.Column('activations', sa.Integer(), nullable=True),
    sa.Column('extra_displays', sa.Integer(), nullable=True),
    sa.Column('c7_score', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sup_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_audits_user_id'), 'field_audits', ['user_id'], unique=False)
    op.create_table('points_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_points_user_time', 'points_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('by_category', sa.JSON(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('red_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('competency', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('open', 'ready', 'closed', name='flagstatus', native_enum=False, length=20), nullable=False),
    sa.Column('opened_score', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('sup_score', sa.Float(), nullable=True),
    sa.Column('sup_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_red_flags_user_status', 'red_flags', ['user_id', 'status'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_code', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.Enum('onboarding', 'quest', 'practice', name='sessionkind', native_enum=False, length=20), nullable=False),
    sa.Column('quest_id', sa.String(length=36), nullable=True),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('revealed', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_user_id'), 'voice_sessions', ['user_id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('scenario_code', sa.String(length=10), nullable=False),
    sa.Column('red_flag_id', sa.String(length=36), nullable=True),
    sa.Column('competency', sa.String(length=4), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['red_flag_id'], ['red_flags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quests_user_day', 'quests', ['user_id', 'day'], unique=False)
    op.create_table('turn_audio',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=60), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'turn_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn_audio')
    op.drop_index('ix_quests_user_day', table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_voice_sessions_user_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index('ix_red_flags_user_status', table_name='red_flags')
    op.drop_table('red_flags')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index('ix_points_user_time', table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index(op.f('ix_field_audits_user_id'), table_name='field_audits')
    op.drop_table('field_audits')
    op.drop_index('ix_assessments_user_comp', table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('users')
    # ### end Alembic commands ###
