"""dday bill scanning

Revision ID: 002
Revises: 001
Create Date: 2026-10-01 17:26:22.035263

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dday_programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('activity', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dday_programs_day'), 'dday_programs', ['day'], unique=False)
    op.create_table('dday_shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['dday_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_shift_user_program')
    )
    op.create_index(op.f('ix_dday_shifts_user_id'), 'dday_shifts', ['user_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'valid', 'review', 'rejected', 'void', name='billstatus', native_enum=False, length=20), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('bill_no', sa.String(length=60), nullable=True),
    sa.Column('store_name', sa.String(length=200), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_vnd', sa.BigInteger(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['dday_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['dday_shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_image_sha256'), 'bills', ['image_sha256'], unique=False)
    op.create_index('ix_bills_program_status', 'bills', ['program_id', 'status'], unique=False)
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    op.create_table('bill_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_events_bill_id'), 'bill_events', ['bill_id'], unique=False)
    op.create_table('bill_images',
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('mime', sa.String(length=40), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_images')
    op.drop_index(op.f('ix_bill_events_bill_id'), table_name='bill_events')
    op.drop_table('bill_events')
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_index('ix_bills_program_status', table_name='bills')
    op.drop_index(op.f('ix_bills_image_sha256'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_dday_shifts_user_id'), table_name='dday_shifts')
    op.drop_table('dday_shifts')
    op.drop_index(op.f('ix_dday_programs_day'), table_name='dday_programs')
    op.drop_table('dday_programs')
    # ### end Alembic commands ###
