apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgnexus
labels:
  - pairs: { app.kubernetes.io/part-of: pgnexus }
resources:
  - namespace.yaml
  - postgres.yaml
  - keycloak.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
configMapGenerator:
  - name: postgres-init
    files: [postgres/init.sql]
  - name: keycloak-realm
    files: [keycloak/pgnexus-realm.json]
